# Generated by Django 5.2.6 on 2025-09-17 20:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bank", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("suspended", "Suspended"),
                ],
                default="active",
                max_length=10,
            ),
        ),
    ]
