# Generated by Django 5.2.6 on 2025-09-20 23:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bank", "0003_alter_transaction_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="reference",
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
